artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/a327cdd27fca4e1b8499e8756afe1172/artifacts
end_time: 1738356104532
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: a327cdd27fca4e1b8499e8756afe1172
run_name: reporting
run_uuid: a327cdd27fca4e1b8499e8756afe1172
source_name: ''
source_type: 4
source_version: ''
start_time: 1738356104494
status: 4
tags: []
user_id: krzysztofwojdalski
