artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/a11bd7849b494addaea19dcc1080a332/artifacts
end_time: 1738356165966
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: a11bd7849b494addaea19dcc1080a332
run_name: reporting
run_uuid: a11bd7849b494addaea19dcc1080a332
source_name: ''
source_type: 4
source_version: ''
start_time: 1738356165940
status: 4
tags: []
user_id: root
