artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/ab3c4ff263b44686aebbcbba2563612c/artifacts
end_time: 1738677735906
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: ab3c4ff263b44686aebbcbba2563612c
run_name: __default__
run_uuid: ab3c4ff263b44686aebbcbba2563612c
source_name: ''
source_type: 4
source_version: ''
start_time: 1738677707796
status: 4
tags: []
user_id: krzysztofwojdalski
