artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/247f4298e26249aebf5b3da86beba125/artifacts
end_time: 1738356501273
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 247f4298e26249aebf5b3da86beba125
run_name: reporting
run_uuid: 247f4298e26249aebf5b3da86beba125
source_name: ''
source_type: 4
source_version: ''
start_time: 1738356501247
status: 4
tags: []
user_id: krzysztofwojdalski
