artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/e6471db1ed4a4e3b9aa66ff2a77d2d4e/artifacts
end_time: 1738621591589
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: e6471db1ed4a4e3b9aa66ff2a77d2d4e
run_name: __default__
run_uuid: e6471db1ed4a4e3b9aa66ff2a77d2d4e
source_name: ''
source_type: 4
source_version: ''
start_time: 1738621591433
status: 3
tags: []
user_id: krzysztofwojdalski
