artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/94366ddcdd71454eb775fd868640dedb/artifacts
end_time: 1738361253192
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 94366ddcdd71454eb775fd868640dedb
run_name: reporting
run_uuid: 94366ddcdd71454eb775fd868640dedb
source_name: ''
source_type: 4
source_version: ''
start_time: 1738361250954
status: 3
tags: []
user_id: krzysztofwojdalski
