artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/1e392656d2164cafbbdcee3330bb7664/artifacts
end_time: 1738357681918
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 1e392656d2164cafbbdcee3330bb7664
run_name: data_science
run_uuid: 1e392656d2164cafbbdcee3330bb7664
source_name: ''
source_type: 4
source_version: ''
start_time: 1738357260989
status: 3
tags: []
user_id: krzysztofwojdalski
