artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/2a7567da29a34fb097f4cef579a2e0a8/artifacts
end_time: 1738691563590
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 2a7567da29a34fb097f4cef579a2e0a8
run_name: data_processing
run_uuid: 2a7567da29a34fb097f4cef579a2e0a8
source_name: ''
source_type: 4
source_version: ''
start_time: 1738691407892
status: 3
tags: []
user_id: krzysztofwojdalski
