artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/28eaa69be80b470c9b61e1b0fdec54e0/artifacts
end_time: 1738668119576
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 28eaa69be80b470c9b61e1b0fdec54e0
run_name: reporting
run_uuid: 28eaa69be80b470c9b61e1b0fdec54e0
source_name: ''
source_type: 4
source_version: ''
start_time: 1738668116348
status: 3
tags: []
user_id: krzysztofwojdalski
