artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/668a4fc206b34becab5c5696fbba9023/artifacts
end_time: 1738356564183
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 668a4fc206b34becab5c5696fbba9023
run_name: reporting
run_uuid: 668a4fc206b34becab5c5696fbba9023
source_name: ''
source_type: 4
source_version: ''
start_time: 1738356564150
status: 4
tags: []
user_id: krzysztofwojdalski
