artifact_location: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082
creation_time: 1738352910847
experiment_id: '338876466534463082'
last_update_time: 1738352910847
lifecycle_stage: active
name: qrt_stock_returns
