artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/824a7999baf34154bddc5cbef65e4f00/artifacts
end_time: 1738361370307
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 824a7999baf34154bddc5cbef65e4f00
run_name: reporting
run_uuid: 824a7999baf34154bddc5cbef65e4f00
source_name: ''
source_type: 4
source_version: ''
start_time: 1738361369538
status: 4
tags: []
user_id: krzysztofwojdalski
