artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/830acfb2d49f4fc08f32f4efa7c7e3fd/artifacts
end_time: 1738356569208
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 830acfb2d49f4fc08f32f4efa7c7e3fd
run_name: reporting
run_uuid: 830acfb2d49f4fc08f32f4efa7c7e3fd
source_name: ''
source_type: 4
source_version: ''
start_time: 1738356569185
status: 4
tags: []
user_id: krzysztofwojdalski
