artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/e1c537def26b46c5a4c8ea17f5b2bafc/artifacts
end_time: 1738360258794
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: e1c537def26b46c5a4c8ea17f5b2bafc
run_name: data_science
run_uuid: e1c537def26b46c5a4c8ea17f5b2bafc
source_name: ''
source_type: 4
source_version: ''
start_time: 1738359920506
status: 3
tags: []
user_id: krzysztofwojdalski
