artifact_uri: file:///Users/krzysztofwojdalski/github_projects/qrt-stock-returns/mlflow_runs/338876466534463082/36856ed4afce48dd8cdd90da4c0ec89c/artifacts
end_time: 1738357352885
entry_point_name: ''
experiment_id: '338876466534463082'
lifecycle_stage: active
run_id: 36856ed4afce48dd8cdd90da4c0ec89c
run_name: reporting
run_uuid: 36856ed4afce48dd8cdd90da4c0ec89c
source_name: ''
source_type: 4
source_version: ''
start_time: 1738357352855
status: 4
tags: []
user_id: krzysztofwojdalski
